name: Intacct .NET SDK CI

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['3.1', '6.x']
        
    name: .NET v${{ matrix.dotnet-version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1
            6.x
      
      - name: Install dependencies for .NET ${{ matrix.dotnet-version }}
        run: dotnet restore
        
      - name: Build
        run: dotnet build
        
      - name: Test
        run: dotnet test
        
      
